version: 2

jobs:
  lint:
    docker:
      - image: circleci/rust:latest
    steps:
      - checkout
      - run: |
          rustup component add clippy
          cargo clippy --all -- --deny warnings
  format:
    docker:
      - image: circleci/rust:latest
    steps:
      - checkout
      - run: cargo fmt -- --check
      
workflows:
  version: 2
  dev:
    jobs:
      - format
      - lint
