version: 2

jobs:
  clippy:
    docker:
      - image: abronan/rust-circleci:latest
    steps:
      - checkout
      - run: cargo clippy --all
      
workflows:
  version: 2
  dev:
    jobs:
      - clippy
