version: 2

jobs:
  clippy:
    docker:
      - image: circleci/rust:latest
    steps:
      - checkout
      - run: |
          rustup component add clippy
          cargo clippy --all
      
workflows:
  version: 2
  dev:
    jobs:
      - clippy
